app:
  api:
    backend:
      url: https://maximal-yew-347818.rj.r.appspot.com
      path:
        login: /user/login
        register: /user/register
        classroom: /classroom
        session: /session
        exercise: /exercise
        question: /question
        pair: /pair

server:
  port : 8081

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    httpclient.wire: DEBUG

messages:
  home: Hit

spring:
  messages:
    use-code-as-default-message: true
    basename: messages
    encoding: UTF-8

  thymeleaf:
    enabled: true
    cache: false
    check-template: true
    check-template-location: true
    encoding: UTF-8
    suffix: .html

  cloud:
    gcp:
      project-id: pareapp-frontend
#      credentials:
#        location: file:[LOCAL_PRIVATE_KEY_FILE]
#        scopes: [SCOPE_1],[SCOPE_2],[SCOPE_3]